# Generated by Django 5.2.4 on 2025-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUsuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('setor', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'auth_usuarios',
            },
        ),
    ]
