# Generated by Django 5.2.4 on 2025-07-22 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('total_numeros', models.IntegerField()),
                ('enviados_certos', models.IntegerField(default=0)),
                ('enviados_errados', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
