# Generated by Django 5.2.4 on 2025-07-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instancias', '0002_delete_instancias'),
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancias',
            fields=[
                ('id_instancia', models.AutoField(primary_key=True, serialize=False)),
                ('name_instancia', models.CharField(max_length=50)),
                ('instancekey', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('inicio_envio', models.DateTimeField(blank=True, null=True)),
                ('termino_envio', models.DateTimeField(blank=True, null=True)),
                ('envios_certos', models.IntegerField(blank=True, default=0, null=True)),
                ('envios_errados', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(blank=True, max_length=30, null=True)),
                ('len_list', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='users.authusuarios')),
            ],
            options={
                'db_table': 'instancias',
            },
        ),
    ]
