# Generated by Django 5.2.4 on 2025-07-31 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0003_initial'),
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(max_length=100)),
                ('mensagem_instancia', models.TextField()),
                ('envios_sucesso', models.PositiveIntegerField(default=0)),
                ('envios_erro', models.PositiveIntegerField(default=0)),
                ('total_envios', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('erro', 'Erro'), ('conectado', 'Conectado')], default='inativa', max_length=50)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_criadas', to='users.authusuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Instancias',
        ),
    ]
