# Generated by Django 5.2.4 on 2025-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0004_instanciaativa_delete_instancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaativa',
            name='numero_instancia',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
