# Generated by Django 5.2.4 on 2025-07-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0006_instanciaativa_id_instancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaativa',
            name='id_instancia',
        ),
    ]
