# Generated by Django 5.2.4 on 2025-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0007_remove_instanciaativa_id_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaativa',
            name='id_instancia',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instanciaativa',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
