# Generated by Django 5.2.4 on 2025-08-03 23:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0008_instanciaativa_id_instancia_and_more'),
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaEncerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instancia', models.CharField(max_length=100)),
                ('mensagem_instancia', models.TextField()),
                ('numero_instancia', models.CharField(max_length=30)),
                ('envios_sucesso', models.PositiveIntegerField(default=0)),
                ('envios_erro', models.PositiveIntegerField(default=0)),
                ('total_envios', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('criada_em', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_instancia', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_encerradas', to='users.authusuarios')),
            ],
        ),
    ]
