# Generated by Django 5.2.4 on 2025-08-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0009_instanciaencerrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaativa',
            name='nome_instancia',
        ),
        migrations.RemoveField(
            model_name='instanciaativa',
            name='numero_instancia',
        ),
        migrations.RemoveField(
            model_name='instanciaativa',
            name='total_envios',
        ),
    ]
