# Generated by Django 5.2.4 on 2025-08-04 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0010_remove_instanciaativa_nome_instancia_and_more'),
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaativa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='instanciaativa',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instancias_criadas', to='users.authusuarios'),
            preserve_default=False,
        ),
    ]
