# Generated by Django 5.2.4 on 2025-08-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0011_remove_instanciaativa_usuario_instanciaativa_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciaativa',
            name='id_instancia',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
