# Generated by Django 5.2.4 on 2025-08-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0012_alter_instanciaativa_id_instancia'),
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaencerrada',
            name='usuario',
        ),
        migrations.AddField(
            model_name='instanciaencerrada',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instancias_encerradas', to='users.authusuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instanciaencerrada',
            name='id_instancia',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
