# Generated by Django 5.2.4 on 2025-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0013_remove_instanciaencerrada_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciaencerrada',
            name='nome_instancia',
            field=models.CharField(max_length=300),
        ),
    ]
